### PR TITLE
Fix: template-k3s is not working as-is (multiple issues)

### LINKED ISSUE #1: Gitpod kernel dependencies not available
### Bug description

The `linux-image-$(uname -r)` (linux-image-5.13.0-1007-gcp) dependency in the .gitpod.yml is no longer available

```bash
$ sudo apt install linux-image-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-image-5.13.0-1007-gcp
E: Couldn't find any package by glob 'linux-image-5.13.0-1007-gcp'
```

This causes the rest of the preparation steps to fail

### Steps to reproduce

Load up template. Tried is a couple of workspaces, including https://turquoise-bat-kelqgteg.ws-eu25.gitpod.io/

### Expected behavior

_No response_

### Example repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by zwindler**
## Description
template-k3s is not working anymore. I tried to run it using the "open in gitpod" link in the [README.md](http://readme.md/) but the scripts were failing directly at start.

Unless I'm mistaken, there are 3 issues in current version.

First: when you launch the workspace, gitpod launches a ubuntu (focal) image on the github host, then tries to install a bunch of stuff in `init` phase of the `.gitpod.yml` file, including the `linux-image-$(uname -r)`.

Unfortunately, gitpod host now seems to run some custom `linux-image-5.16.20-051620-generic` which is not available in repos from /etc/apt/sources.list. You *could* install packages directly from [kernel-ppa](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.16.20/amd64/) but that seems tedious to automate in the script, for future versions.

So I went for the workaround proposed in #1 issue, I installed `linux-image-generic` instead, which seems to be "ok", even though it's probably not really clean.

Second: the `.gitpod/prepare-rootfs.sh` script fails at line 17 (tar) because the hirsute image is not available anymore (404)!

I switched all references to this images to jammy, which should be around for some time since it's an LTS

Third: qemu, nc and kernel modules are installed during prebuild only. BUT:
> Prebuilds save only the workspace directory. Other directories like the home directory are not saved by prebuilds.

That's an issue, because we also need qemu and kernel modules for script (command statement) `.gitpod\[qemu.sh](http://qemu.sh/)`, and nc for `.gitpod/prepare-k3s.sh`

I add to re-install them in appropriate order

## Related Issue(s)
Probably Fixes #1 as well

## How to test
Open my [repository in gitpod with these fixes](https://gitpod.io/#https://github.com/zwindler/gitpod-template-k3s)

## Release Notes
```release-note
fixes linux-image missing package
fixes hirsute-server-cloudimg no longer available
fixes missing packages needed for scripts in "command" step
```

## Documentation

### CODE REVIEW

**Comment by sagor999** [comment]
@zwindler thank you for PR!! :heart: 

Couple of notes:
I see this in terminal for `prepare k3s`: `.gitpod/prepare-k3s.sh: line 14: nc: command not found`
can you fix it?

Tried to launch ssh.sh but getting:
`./ssh.sh: line 3: sshpass: command not found`

Not sure if related to your PR or if it was broken prior as well. :thinking:

**Comment by zwindler** [comment]
Thanks for the review :-)

I know how to fix the `nc not found`. I had trouble with the fact that both terminal launch `apt install` at the same time, one of them failing because the other was locking. I'll add a little loop to deal with this properly.

I'll check the `sshpass` because I don't know yet what's the issue.

**Comment by zwindler** [comment]
@sagor999 can you check again with my latest modifications if that's better?

**Review by sagor999 — APPROVED** [review]
Awesome work! Thank you! :heart:

**Pull request merged**
